# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea5450579de53fcb18ffe62c7482d640298d42910e7d73ef32d1660b33b92ae7e6375f275eb4555c49a43faae7ae7d2277199ee665527e5cde833d47aa038723

test:
  secret_key_base: 4cfeba229d4360884d75080a093c1ddaeeadeba0dede5cc5fef8da021d7eab4674dd542179ea77136587112213255cc2929b164e9bd0c99159b9fbfbaad07005

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
